"""record.py WT ID ENTRY DUMP_RC BUILD_RC ARENA LOGDIR V0_QKV V0_ATTN V0_FFN

Writes <WT>/auto/results/<ID>.json (merging <LOGDIR>/<ID>.makespan.json and the Arena log
summary), copies the logs into <WT>/auto/logs, and regenerates <WT>/auto/BOARD.md from every
result file. Pure stdlib; called by driver.sh after each queue entry.
"""
import glob
import json
import os
import re
import shutil
import sys
import time

wt, ident, entry, dump_rc, build_rc, arena, logdir = sys.argv[1:8]
v0 = [float(x) for x in sys.argv[8:11]]
kernels = ["sliding_project_qkv", "sliding_attention_output", "decoder_feedforward"]
short = {"sliding_project_qkv": "qkv", "sliding_attention_output": "attn_out", "decoder_feedforward": "ffn"}

res_dir = os.path.join(wt, "auto", "results")
log_dst = os.path.join(wt, "auto", "logs")
os.makedirs(res_dir, exist_ok=True)
os.makedirs(log_dst, exist_ok=True)

path = os.path.join(res_dir, f"{ident}.json")
rec = {}
if os.path.exists(path):
    try:
        rec = json.load(open(path))
    except Exception:  # noqa: BLE001
        rec = {}
rec.update({"id": ident, "entry": entry, "updated": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())})
try:
    rec["commit"] = open(os.path.join(logdir, f"{ident}.commit")).read().strip()
except Exception:  # noqa: BLE001
    pass
rec["dump_rc"] = dump_rc
rec["build_rc"] = build_rc
rec["arena"] = arena

try:
    ms = json.load(open(os.path.join(logdir, f"{ident}.makespan.json")))
    rec["makespan"] = {short[k]: (ms.get(k) or {}).get("makespan") for k in kernels}
    rec["busy"] = {short[k]: (ms.get(k) or {}).get("busy") for k in kernels}
except Exception:  # noqa: BLE001
    rec.setdefault("makespan", {s: None for s in short.values()})

# Arena log summary: the job verdict plus every line that mentions cycles or a pass/fail.
arena_log = os.path.join(logdir, f"{ident}.arena.log")
if os.path.exists(arena_log):
    lines = open(arena_log, errors="replace").read().splitlines()
    keep = [l for l in lines if re.search(r"cycle|passed|failed|FAIL|PASS|tolerance|error|submitted job|exit", l, re.I)]
    rec["arena_lines"] = keep[:80]
    rec["arena_accuracy"] = "PASS" if any("all kernel tests passed" in l for l in lines) else ("FAIL" if arena == "fail" else "?")

# Compile errors: first error line of the dump log, if any.
dump_log = os.path.join(logdir, f"{ident}.dump.log")
if os.path.exists(dump_log):
    errs = [l for l in open(dump_log, errors="replace").read().splitlines() if l.startswith("error") or "error[" in l or "internal compiler error" in l]
    rec["first_error"] = errs[0][:300] if errs else None

json.dump(rec, open(path, "w"), indent=1, ensure_ascii=False)

for suffix in ("dump.log", "build.log", "arena.log", "makespan.json"):
    src = os.path.join(logdir, f"{ident}.{suffix}")
    if os.path.exists(src):
        # keep the last 400 lines of logs to bound the repository size
        if suffix.endswith(".log"):
            tail = open(src, errors="replace").read().splitlines()[-400:]
            open(os.path.join(log_dst, f"{ident}.{suffix}"), "w").write("\n".join(tail) + "\n")
        else:
            shutil.copyfile(src, os.path.join(log_dst, f"{ident}.{suffix}"))


def geomean(m):
    vals = [m.get("qkv"), m.get("attn_out"), m.get("ffn")]
    if any(v is None or not v for v in vals):
        return None
    sp = [v0[i] / vals[i] for i in range(3)]
    return (sp[0] * sp[1] * sp[2]) ** (1 / 3)


rows = []
for f in sorted(glob.glob(os.path.join(res_dir, "*.json")), key=os.path.getmtime):
    try:
        r = json.load(open(f))
    except Exception:  # noqa: BLE001
        continue
    m = r.get("makespan") or {}
    g = geomean(m)
    fmt = lambda v: f"{v:,}" if isinstance(v, int) else "—"  # noqa: E731
    rows.append(
        f"| `{r.get('entry','?')}` | {r.get('commit','')} | {fmt(m.get('qkv'))} | {fmt(m.get('attn_out'))} | {fmt(m.get('ffn'))} | "
        f"{(f'{g:.3f}' if g else '—')} | {'ok' if str(r.get('dump_rc')) == '0' else r.get('dump_rc')} | "
        f"{'ok' if str(r.get('build_rc')) == '0' else r.get('build_rc')} | {r.get('arena','')} | {r.get('arena_accuracy','')} | "
        f"{(r.get('first_error') or '')[:80].replace('|','/')} | {r.get('updated','')} |"
    )

board = [
    "# auto/BOARD.md — unattended chain results (regenerated by scripts/dev/auto/record.py)",
    "",
    "makespan = static schedule span (screening only, RULES §5). `arena`: pending = pod not logged in when the entry ran "
    "(retried automatically), pass/fail = Arena job verdict, n/a = build failed. Raw logs: auto/logs/<id>.*",
    "",
    "| entry | commit | qkv | attn_out | ffn | geomean vs V0 | dump | build | arena | accuracy | first error | updated (UTC) |",
    "|---|---|---:|---:|---:|---:|:---:|:---:|:---:|:---:|---|---|",
    *rows,
    "",
]
open(os.path.join(wt, "auto", "BOARD.md"), "w").write("\n".join(board))
print(f"recorded {ident}: {rec.get('makespan')} arena={arena}")
